-- 코드를 입력하세요
SELECT
    CP.CART_ID
FROM CART_PRODUCTS AS CP
INNER JOIN CART_PRODUCTS AS CP2 ON CP.CART_ID = CP2.CART_ID AND CP2.NAME="Yogurt"
WHERE CP.NAME = "Milk"
GROUP BY CP.CART_ID
ORDER BY CP.CART_ID ASC